//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class BANGXEPHANG
    {
        public string MaDoi { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Thua { get; set; }
        public Nullable<int> Hoa { get; set; }
        public Nullable<int> HieuSo { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<int> SoBanThangSanKhach { get; set; }
        public Nullable<int> XepHang { get; set; }
    
    }
}
