//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class CAUTHU
    {
        public CAUTHU()
        {
        }
    
        public string MaCauThu { get; set; }
        public string TenCauThu { get; set; }
        public Nullable<byte> SoAo { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<System.DateTime> NgayRoiDi { get; set; }
        public string MaLoaiCauThu { get; set; }
        public string GhiChu { get; set; }
        public string MaDoi { get; set; }
        public Nullable<int> SoBanThang { get; set; }
    
      
    }
}
