//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class CHITIETTHAYNGUOI
    {
        public string MaThayNguoi { get; set; }
        public string MaCauThuVaoSan { get; set; }
        public string MaCauThuRaSan { get; set; }
        public System.TimeSpan ThoiDiem { get; set; }
        public string MaTranDau { get; set; }
    
    }
}
