//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class DIEUKIEN
    {
        public string MaMuaGiai { get; set; }
        public int TuoiToiThieu { get; set; }
        public int TuoiToiDa { get; set; }
        public int SoCauThuToiThieu { get; set; }
        public int SoCauThuToiDa { get; set; }
        public int SoCauThuNuocNgoaiToiDa { get; set; }
        public int SoLanThayNguoiToiDa { get; set; }
        public int DiemSoThang { get; set; }
        public int DiemSoThua { get; set; }
        public int DiemSoHoa { get; set; }
    
    }
}
