//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class DIEUKIEN
    {
        public string MaMuaGiai { get; set; }
        public Nullable<int> TuoiToiThieu { get; set; }
        public Nullable<int> TuoiToiDa { get; set; }
        public Nullable<int> SoCauThuToiThieu { get; set; }
        public Nullable<int> SoCauThuToiDa { get; set; }
        public Nullable<int> SoCauThuNuocNgoaiToiDa { get; set; }
        public Nullable<int> SoLanThayNguoiToiDa { get; set; }
        public Nullable<int> DiemSoThang { get; set; }
        public Nullable<int> DiemSoThua { get; set; }
        public Nullable<int> DiemSoHoa { get; set; }
    
    }
}
