//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class DOIBONG
    {
        public DOIBONG()
        {
           
        }
    
        public string MaDoi { get; set; }
        public string MaMuaGiai { get; set; }
        public string TenDoi { get; set; }
    
       
    }
}
