//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class KETQUADOIBONG
    {
        public string MaDoi { get; set; }
        public int Thang { get; set; }
        public int Thua { get; set; }
        public int Hoa { get; set; }
        public int HieuSo { get; set; }
        public int Diem { get; set; }
        public int SoBanThangSanKhach { get; set; }
    
    }
}
