//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class LOAIBANTHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIBANTHANG()
        {
        }
    
        public string MaLoaiBanThang { get; set; }
        public string MaMuaGiai { get; set; }
        public string TenLoaiBanThang { get; set; }
        public Nullable<bool> TinhBanChoCauThu { get; set; }
    
      
    }
}
