//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class LOAICAUTHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAICAUTHU()
        {
        }
    
        public string MaLoaiCauThu { get; set; }
        public string TenLoaiCauThu { get; set; }
        public Nullable<bool> CauThuNuocNgoai { get; set; }
        public string MaMuaGiai { get; set; }
    

    }
}
