//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class MUAGIAI
    {
        public MUAGIAI()
        {
           
        }
    
        public string MaMuaGiai { get; set; }
        public string TenMuaGiai { get; set; }
        public int TrangThai { get; set; }
    
      
    }
}
