//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class SANTHIDAU
    {
        public SANTHIDAU()
        {
            
        }
    
        public string MaSanThiDau { get; set; }
        public string TenSanThiDau { get; set; }
        public string MaMuaGiai { get; set; }
        public string DonViSoHuu { get; set; }
        public string MaDoiNha { get; set; }
    
      
    }
}
