//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class TRANDAU
    {
        public TRANDAU()
        {
           
        }
    
        public string MaTranDau { get; set; }
        public string MaMuaGiai { get; set; }
        public string DoiChuNha { get; set; }
        public string DoiKhach { get; set; }
        public Nullable<System.DateTime> NgayThiDau { get; set; }
        public Nullable<System.DateTime> NgayThiDauChinh { get; set; }
        public Nullable<System.TimeSpan> GioThiDau { get; set; }
        public Nullable<System.TimeSpan> GioThiDauChinh { get; set; }
        public string MaSanThiDau { get; set; }
        public string MaSanThiDauChinh { get; set; }
        public Nullable<int> SoBanThangDoiNha { get; set; }
        public Nullable<int> SoBanThangDoiKhach { get; set; }
        public Nullable<System.TimeSpan> ThoiGianThiDau { get; set; }
        public string MaVongDau { get; set; }
    
       
    }
}
