//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaiVoDich.DTO_Class.Class
{
    using System;
    using System.Collections.Generic;
    
    public class TRANDAU
    {
        public TRANDAU()
        {
           
        }
    
        public string MaTranDau { get; set; }
        public string MaMuaGiai { get; set; }
        public string DoiChuNha { get; set; }
        public string DoiKhach { get; set; }
        public System.DateTime NgayThiDau { get; set; }
        public System.DateTime NgayThiDauChinh { get; set; }
        public System.TimeSpan GioThiDau { get; set; }
        public System.TimeSpan GioThiDauChinh { get; set; }
        public string MaSanThiDau { get; set; }
        public string MaSanThiDauChinh { get; set; }
        public int SoBanThangDoiNha { get; set; }
        public int SoBanThangDoiKhach { get; set; }
        public System.TimeSpan ThoiGianThiDau { get; set; }
        public string MaVongDau { get; set; }
    
       
    }
}
